# Generated by Django 3.1.12 on 2025-09-11 06:26

from django.db import migrations, models
import django.db.models.deletion
import ticketapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ticketapp.models.getFileName)),
                ('showing_time', models.CharField(default='comming soon..', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Shows',
        ),
    ]
