# Generated by Django 3.1.12 on 2025-09-16 05:31

from django.db import migrations, models
import ticketapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_auto_20250911_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ticketapp.models.getFileName),
        ),
    ]
