# Generated by Django 3.1.12 on 2025-09-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Comedyshow',
        ),
    ]
