# Generated by Django 3.1.12 on 2025-09-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_auto_20250916_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedyshow',
            name='Categorys',
        ),
    ]
