# Generated by Django 3.1.12 on 2025-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_remove_comedyshow_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedyshow',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
