# Generated by Django 3.1.12 on 2025-09-16 11:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_auto_20250916_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedyshow',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comedyshow',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='comedyshow',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comedyshow',
            name='showing_time',
            field=models.CharField(max_length=100),
        ),
    ]
