# Generated by Django 3.1.12 on 2025-09-16 11:17

from django.db import migrations, models
import ticketapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20250916_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedyshow',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comedyshow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ticketapp.models.getFileName),
        ),
        migrations.AlterField(
            model_name='comedyshow',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='comedyshow',
            name='showing_time',
            field=models.CharField(default='comming soon..', max_length=100),
        ),
    ]
