# Generated by Django 3.1.12 on 2025-09-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0010_auto_20250917_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedyshow',
            name='Categorys',
        ),
        migrations.RemoveField(
            model_name='movieticket',
            name='Categorys',
        ),
        migrations.RemoveField(
            model_name='musicconsert',
            name='Categorys',
        ),
        migrations.RemoveField(
            model_name='sportsevent',
            name='Categorys',
        ),
    ]
