# Generated by Django 3.1.12 on 2025-09-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0011_auto_20250917_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieticket',
            name='showing_time',
        ),
        migrations.AddField(
            model_name='movieticket',
            name='showing',
            field=models.CharField(default='Upcomming...', max_length=100),
        ),
    ]
