# Generated by Django 3.1.12 on 2025-09-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0012_auto_20250917_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieticket',
            old_name='nowShowing',
            new_name='nowShowing_or_Imdb',
        ),
    ]
