# Generated by Django 3.1.12 on 2025-09-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0013_auto_20250917_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieticket',
            old_name='nowShowing_or_Imdb',
            new_name='nowShowing',
        ),
        migrations.RenameField(
            model_name='movieticket',
            old_name='showing',
            new_name='showing_or_IMDB',
        ),
    ]
