# Generated by Django 3.1.12 on 2025-09-23 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticketapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketapp', '0014_auto_20250917_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='Age',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='Available_sheet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='Date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='Duration',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='Location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='Premium_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='Time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='discription',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='nowShowing',
            field=models.BooleanField(default=False, help_text='1-show,0-Hidden'),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='upcoming',
            field=models.BooleanField(default=False, help_text='1-show,0-Hidden'),
        ),
        migrations.AddField(
            model_name='movieticket',
            name='D_quality',
            field=models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='movieticket',
            name='carosel_image',
            field=models.ImageField(blank=True, null=True, upload_to=ticketapp.models.getFileName),
        ),
        migrations.AddField(
            model_name='movieticket',
            name='discription',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movieticket',
            name='timing',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movieticket',
            name='upcoming_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movieticket',
            name='upcoming_language',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='Age',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='Available_sheet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='Date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='Duration',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='Location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='Premium_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='Time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='discription',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='nowShowing',
            field=models.BooleanField(default=False, help_text='1-Show,0-Hidden'),
        ),
        migrations.AddField(
            model_name='musicconsert',
            name='upcoming',
            field=models.BooleanField(default=False, help_text='1-Show,0-Hidden'),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='Age',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='Available_sheet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='Date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='Duration',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='Location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='Premium_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='Time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='discription',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='nowShowing',
            field=models.BooleanField(default=False, help_text='1-show,0-Hidden'),
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='upcoming',
            field=models.BooleanField(default=False, help_text='1-show,0-Hidden'),
        ),
        migrations.CreateModel(
            name='Book_Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_ticket', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.sportsevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
