# Generated by Django 3.1.12 on 2025-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0015_auto_20250923_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link_name',
            field=models.CharField(default='default-link', max_length=150),
        ),
    ]
