# Generated by Django 3.1.12 on 2025-09-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0016_auto_20250923_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_ticket',
            name='Total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
