# Generated by Django 3.1.12 on 2025-09-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0017_book_ticket_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_ticket',
            name='sport',
        ),
        migrations.AddField(
            model_name='book_ticket',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book_ticket',
            name='event_type',
            field=models.CharField(choices=[('sport', 'SportsEvent'), ('music', 'MusicConsert'), ('comedy', 'ComedyShow')], default='sport', max_length=50),
        ),
    ]
