# Generated by Django 3.1.12 on 2025-09-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0018_auto_20250924_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_ticket',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='book_ticket',
            name='event_type',
        ),
        migrations.AddField(
            model_name='book_ticket',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.sportsevent'),
        ),
    ]
