# Generated by Django 3.1.12 on 2025-09-24 08:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketapp', '0019_auto_20250924_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Ticket',
            new_name='Sports_Ticket',
        ),
    ]
