# Generated by Django 3.1.12 on 2025-09-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0021_music_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_ticket',
            old_name='sport',
            new_name='music',
        ),
    ]
