# Generated by Django 3.1.12 on 2025-09-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0023_comedy_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comedy_ticket',
            old_name='music',
            new_name='comedy',
        ),
    ]
