# Generated by Django 3.1.12 on 2025-09-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0025_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.FloatField(default=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.movieticket')),
            ],
        ),
    ]
