# Generated by Django 3.1.12 on 2025-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0026_movietiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='show_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='show_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
