# Generated by Django 3.1.12 on 2025-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0027_auto_20250925_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_ticket',
            name='Total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sports_ticket',
            name='Total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sports_ticket',
            name='Total_ticket',
            field=models.IntegerField(default=1),
        ),
    ]
