# Generated by Django 3.1.12 on 2025-09-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0028_auto_20250926_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsevent',
            name='Available_sheet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sportsevent',
            name='Premium_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sportsevent',
            name='discription',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sportsevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sports/'),
        ),
        migrations.AlterField(
            model_name='sportsevent',
            name='nowShowing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sportsevent',
            name='showing_time',
            field=models.CharField(default='coming soon..', max_length=100),
        ),
        migrations.AlterField(
            model_name='sportsevent',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
